version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t barcus/bareos-director:latest director-mysql/19.2-ubuntu
     - run: docker push barcus/bareos-director:latest
