## docker-compose Bareos Director/Storage/Client/webUI, PHP-FPM and MySQL Database based on Alpine
version: '3'
services:
  bareos-dir:
    image: barcus/bareos-director:20-alpine-pgsql
    volumes:
      - /data/bareos/data/director:/var/lib/bareos # required for MyCatalog backup
    environment:
      - DB_INIT=true
      - DB_UPDATE=false
      - DB_HOST=bareos-db
      - DB_PORT=5432
      - DB_NAME=bareos
      - DB_USER=bareos
      - DB_PASSWORD=${DB_PASSWORD} # defined in .env file
      - DB_ADMIN_USER=${DB_ADMIN_USER} # defined in .env file
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD} # defined in .env file
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD} # defined in .env file
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD} # defined in .env file
      - BAREOS_WEBUI_PASSWORD=${BAREOS_WEBUI_PASSWORD} # defined in .env file
      - SMTP_HOST=smtpd
      - ADMIN_MAIL=your@mail.address # Change me!
      # Optional you can gets backup notification via Slack or Telegram
      - WEBHOOK_NOTIFICATION=false # true or false if set to true email notification gets disabled
      - WEBHOOK_TYPE=slack # choose slack or telegram
      - WEBHOOK_URL= # set the slack or telegram URL
      - WEBHOOK_CHAT_ID= # for telegram only set the <chat_id>
    depends_on:
      - bareos-db

  bareos-sd:
    image: barcus/bareos-storage:20-alpine
    ports:
      - 9103:9103
    volumes:
      - /data/bareos/data/storage:/var/lib/bareos/archive
    environment:
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD} # defined in .env file

  bareos-fd:
    image: barcus/bareos-client:20-alpine
    volumes:
      - /data/bareos/data/director:/var/lib/bareos-director # required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD} # defined in .env file
      - FORCE_ROOT=false
      #- PUID=1500 # force bareos user ID
      #- PGID=1500 # force bareos group ID

  bareos-webui:
    image: barcus/bareos-webui:20-alpine
    ports:
      - 8080:9100
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    volumes:
      - /data/bareos/config/webui:/etc/bareos-webui
      - /data/bareos/data/webui:/usr/share/bareos-webui
    depends_on:
      - php-fpm

  php-fpm:
    image: barcus/php-fpm-alpine
    volumes:
      - /data/bareos/config/webui:/etc/bareos-webui
      - /data/bareos/data/webui:/usr/share/bareos-webui

  bareos-db:
    image: postgres:14
    volumes:
      - /data/pgsql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_ADMIN_USER} # defined in .env file
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD} # defined in .env file
      - POSTGRES_INITDB_ARGS=--encoding=SQL_ASCII

  smtpd:
    image: namshi/smtp
#EOF
