## docker-compose Bareos Director/Storage/Client/webUI, PHP-FPM and MySQL Database based on Alpine
version: '3'
services:
  bareos-dir:
    image: barcus/bareos-director:19-alpine
    volumes:
      - /data/bareos/data/director:/var/lib/bareos # required for MyCatalog backup
    environment:
      - DB_HOST=bareos-db
      - DB_PORT=3306
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=bareos
      - DB_USER=root
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD}
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD}
      - BAREOS_WEBUI_PASSWORD=${BAREOS_WEBUI_PASSWORD}
      - SMTP_HOST=smtpd
      - ADMIN_MAIL=${ADMIN_MAIL}
      # Optional you can gets backup notification via Slack or Telegram
      - WEBHOOK_NOTIFICATION=false # true or false if set to true email notification gets disabled
      - WEBHOOK_TYPE=slack # choose slack or telegram
      - WEBHOOK_URL= # set the slack or telegram URL
      - WEBHOOK_CHAT_ID= # for telegram only set the <chat_id>
    depends_on:
      - bareos-db

  bareos-sd:
    image: barcus/bareos-storage:19-alpine
    ports:
      - 9103:9103
    volumes:
      - /data/bareos/data/storage:/var/lib/bareos/archive
    environment:
      - BAREOS_SD_PASSWORD=${BAREOS_SD_PASSWORD}

  bareos-fd:
    image: barcus/bareos-client:19-alpine
    volumes:
      - /data/bareos/data/director:/var/lib/bareos-director # required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=${BAREOS_FD_PASSWORD}
      - FORCE_ROOT=false

  bareos-webui:
    image: barcus/bareos-webui:19-alpine
    ports:
      - 8080:9100
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    volumes:
      - /data/bareos/config/webui:/etc/bareos-webui
      - /data/bareos/data/webui:/usr/share/bareos-webui
    depends_on:
      - php-fpm

  php-fpm:
    image: barcus/php-fpm-alpine
    volumes:
      - /data/bareos/config/webui:/etc/bareos-webui
      - /data/bareos/data/webui:/usr/share/bareos-webui

  bareos-db:
    image: mysql:5.6
    volumes:
      - /data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  smtpd:
    image: namshi/smtp
#EOF
