name: ci-storage

on:
  push:
    paths:
      - 'storage*/**'
      - '.github/workflows/ci-storage.yml'
      - '.github/actions/prepare-bareos-build/*'
      - '.github/actions/build-bareos-app/*'
      - '.github/actions/push-bareos-app/*'
    branches:
      - master
      - work_lint
  pull_request:
    paths:
      - 'storage*/**'
      - '.github/workflows/ci-storage.yml'
      - '.github/actions/prepare-bareos-build/*'
      - '.github/actions/build-bareos-app/*'
      - '.github/actions/push-bareos-app/*'
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare build file
        uses: ./.github/actions/prepare-bareos-build
        with:
          bareos_app: storage

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact-storage
          path: build

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build-artifact-storage
          path: build

      - name: Build images
        uses: ./.github/actions/build-bareos-app
        with:
          bareos_app: storage

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact-storage
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build-artifact-storage
          path: build

      - name: Load and push images
        uses: ./.github/actions/push-bareos-app
        with:
          docker_pass: ${{ secrets.DOCKER_PASS }}
          bareos_app: storage
