name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Prepare build file
      run: |
        export BAREOS_APP='director'
        ./build.sh
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Build images
      run: cat file.build
