name: test-compose

on:
  push:
    paths:
      - 'docker-compose*'
      - '.github/workflows/test-compose.yml'
    branches:
      - master
      - ci_compose
  pull_request:
    paths:
      - 'docker-compose*'
      - '.github/workflows/test-compose.yml'
    branches:
      - master

jobs:
  test-compose:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [alpine-v1, alpine-v2, ubuntu-mysql, ubuntu-pgsql]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run docker-compose
        run: docker-compose -f docker-compose-${{ matrix.module }}.yml up
