name: webui

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare build file
        uses: ./.github/actions/prepare-bareos-build
        with:
          bareos_app: webui

      - name: Build images
        uses: ./.github/actions/build-bareos-app

      - name: Upload images
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: build/

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build file
        uses: actions/download-artifact@v1
        with:
          name: build-artifact

      - name: Load images
        uses: ./.github/actions/push-bareos-app

      - name: Run Docker image
        run: docker images

      - name: Create manifests
        run: echo 'Create manifests'
     
      - name: push manifests
        run: echo 'Push manifests'
